[mcp_servers.21st]
url = "https://21st.dev/api/mcp"

[mcp_servers.21st.http_headers]
x-api-key = "21st_sk_b5474aef97e059c903894aa2323422513265720324ea87491662482768bce0e1"

[mcp_servers.wavespeed]
command = "/Users/clement/.local/bin/uvx"
args = ["wavespeed-mcp"]

[mcp_servers.wavespeed.env]
WAVESPEED_API_KEY = "wsk_live_36cm3egCfTmUgYLD0jPyDNNA55TzT-_CPPsBXT6NmAk"
