(function(){'use strict';
const root=document.getElementById('matchRoot');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const empty=t=>`<div class="empty">${esc(t)}</div>`;
const panel=(title,body,extra='')=>`<section class="panel ${extra}"><h2 class="panel-title">${esc(title)}</h2>${body}</section>`;
const logo=(url,name)=>url?`<img src="${esc(url)}" alt="${esc(name)}">`:'';
const list=(items,cls='reason-list')=>`<ul class="${cls}">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;

function header(vm){const i=vm.identity;return `<div class="match-head"><div class="meta-row"><div class="league">${logo(i.league.logo,i.league.name)}<span>${esc(i.league.name)}</span></div><span>${esc(i.date||'Date à confirmer')}</span></div><div class="teams"><div class="team">${logo(i.home.logo,i.home.name)}<h1>${esc(i.home.name)}</h1><small>Domicile</small></div><div class="versus"><b>VS</b><i></i><time>${esc(i.time||'—')}</time></div><div class="team">${logo(i.away.logo,i.away.name)}<h1>${esc(i.away.name)}</h1><small>Extérieur</small></div></div>${vm.conditions.venue?`<div class="venue">⌾ ${esc(vm.conditions.venue)}</div>`:''}<div class="tabs" role="tablist"><button class="tab active" data-tab="summary">Résumé</button><button class="tab" data-tab="advanced">Données avancées</button><button class="tab" data-tab="players">Joueurs</button></div></div>`}

function summary(vm){const r=vm.model.recommendation;const decision=r?`<div class="decision"><div><div class="decision-label">Décision IASHARK</div><h2>${esc(r.market)}</h2><p class="copy">Le marché affiché est celui retenu par le modèle avec les données actuellement validées.</p></div>${r.probability!==null?`<div><div class="big-number">${r.probability}%</div><div class="metric-label">Probabilité modèle</div></div>`:''}</div>`:`<div class="status">${esc(vm.model.unavailableReason)}</div>`;
const reading=vm.editorial.reading?`<p class="copy">${esc(vm.editorial.reading)}</p>`:empty('La lecture éditoriale sera publiée quand les données du match seront suffisamment complètes.');
const reasons=[...vm.editorial.reasons];if(vm.editorial.decisiveFactor)reasons.push(vm.editorial.decisiveFactor);
return `<div class="grid two">${panel('Lecture du match',reading)}${panel('Décision IASHARK',decision)}</div><div class="grid two" style="margin-top:10px">${panel('Pourquoi cette décision ?',reasons.length?list(reasons):empty('Aucun facteur décisif fiable n’est encore publié.'))}${panel('Risque principal',r?`<p class="copy">Cette estimation dépend de la qualité et de l’actualité des données disponibles. Vérifiez les compositions avant le coup d’envoi.</p>`:empty('Pas de recommandation tant que les données sont insuffisantes.'))}</div>`}

function probabilities(vm){const p=vm.model.probabilities;if(!p)return empty('Probabilités indisponibles.');return `<div class="probabilities"><div><strong>${p.home}%</strong><span class="metric-label">${esc(vm.identity.home.name)}</span></div><div><strong>${p.draw}%</strong><span class="metric-label">Nul</span></div><div><strong>${p.away}%</strong><span class="metric-label">${esc(vm.identity.away.name)}</span></div></div>`}
function xg(vm){const x=vm.model.expectedGoals;if(!x)return empty('xG indisponibles pour ce match.');return `<div class="xg-teams"><div>${logo(vm.identity.home.logo,vm.identity.home.name)}<strong>${x.home.toFixed(2)}</strong><span class="metric-label">${esc(vm.identity.home.name)}</span></div><div>${logo(vm.identity.away.logo,vm.identity.away.name)}<strong>${x.away.toFixed(2)}</strong><span class="metric-label">${esc(vm.identity.away.name)}</span></div></div>`}
function scores(vm){return vm.model.scores.length?vm.model.scores.map(s=>`<div class="score"><strong>${esc(s.score)}</strong><span>${s.probability}%</span></div>`).join(''):empty('Scores probables indisponibles.')}
function comparison(vm){if(!vm.comparison)return empty('Comparaison indisponible : échantillon insuffisant.');return vm.comparison.rows.map(r=>{const max=Math.max(r.home,r.away,1);return `<div class="compare-row"><span>${r.home}</span><div class="bar"><i style="width:${r.home/max*100}%"></i></div><div class="compare-label">${esc(r.label)}</div><div class="bar away"><i style="width:${r.away/max*100}%"></i></div><span>${r.away}</span></div>`}).join('')}
function patterns(vm){if(!vm.patterns)return empty('Scénario par tranches indisponible : cinq matchs fiables minimum sont requis.');const h=vm.patterns.home.slots,a=vm.patterns.away.slots,max=Math.max(...h.map(x=>+x.n||0),...a.map(x=>+x.n||0),1);return `<div class="patterns">${h.map((x,n)=>`<div class="pattern-slot"><div class="pattern-bars"><i style="height:${(+x.n||0)/max*90}px"></i><i class="away" style="height:${(+a[n].n||0)/max*90}px"></i></div><small>${esc(x.t)}</small></div>`).join('')}</div>`}
function conditions(vm){const c=vm.conditions;const rows=[];if(c.venue)rows.push(`<li><b>Stade :</b> ${esc(c.venue)}</li>`);if(c.weather)rows.push(`<li><b>Météo :</b> ${esc(c.weather.temperature)} · ${esc(c.weather.description)} <small>(${esc(c.weather.source)})</small></li>`);return rows.length?`<ul class="source-list">${rows.join('')}</ul>`:empty('Conditions non confirmées.')}
function referee(vm){if(!vm.referee)return empty('Arbitre non encore désigné ou statistiques disciplinaires indisponibles.');const a=vm.referee;return `<p class="copy"><b>${esc(a.nom)}</b>${a.cartons_match!=null?` · ${esc(a.cartons_match)} cartons/match`:''}${a.penalties_match!=null?` · ${esc(a.penalties_match)} penaltys/match`:''}</p>`}
function faq(vm){const model=vm.model.available?'Oui. Les données ont franchi le seuil minimal de qualité du moteur.':'Non. IASHARK masque les probabilités quand les données ne sont pas assez fiables.';return `<div class="faq"><details open><summary>Les probabilités sont-elles disponibles ?</summary><p>${esc(model)}</p></details><details><summary>D’où viennent les données affichées ?</summary><p>${esc(vm.model.sources.join(' · ')||'API-Football pour le calendrier et les équipes.')}</p></details><details><summary>Pourquoi certains blocs peuvent-ils manquer ?</summary><p>Une section n’apparaît que si sa source et son échantillon sont suffisants. Aucun zéro n’est utilisé pour remplacer une donnée absente.</p></details></div>`}
function advanced(vm){const quality=vm.model.available?`<div class="quality"><div><strong>${vm.model.quality}%</strong><div class="metric-label">Qualité des données</div></div><div><strong>${vm.model.simulationCount?vm.model.simulationCount.toLocaleString('fr-FR'):'—'}</strong><div class="metric-label">Simulations exécutées</div></div><div><strong>${vm.model.sources.length}</strong><div class="metric-label">Sources confirmées</div></div></div>`:empty(vm.model.unavailableReason);return `<div class="grid two">${panel('Conditions du match',conditions(vm))}${panel('Arbitre & discipline',referee(vm))}</div><div class="grid three" style="margin-top:10px">${panel('Probabilités 1X2',probabilities(vm))}${panel('Buts attendus (xG)',xg(vm))}${panel('Scores les plus probables',scores(vm))}</div><div style="margin-top:10px">${panel('Comparaison des équipes',comparison(vm))}</div><div style="margin-top:10px">${panel('Scénario par tranches de 15 min',patterns(vm))}</div><div class="grid two" style="margin-top:10px">${panel('Qualité et calcul',quality)}${panel('Sources utilisées',list(vm.model.sources,'source-list'))}</div><div style="margin-top:10px">${panel('Questions sur ce match',faq(vm))}</div>`}

function players(vm){const p=vm.players;const abs=(team,items)=>`<div><div class="decision-label">${esc(team.name)}</div>${items.length?list(items.map(x=>`${x.name}${x.reason?` — ${x.reason}`:''}`),'absence-list'):empty('Aucune absence confirmée dans les données.')}</div>`;const watches=p.watch.length?`<div class="watch-grid">${p.watch.map(x=>`<div class="watch">${x.photo?`<img src="${esc(x.photo)}" alt="">`:''}<div><b>${esc(x.name)}</b><small>${x.value!==null?`${x.value} contribution(s) récente(s)`:'Joueur à suivre'}</small></div></div>`).join('')}</div>`:empty('Aucun joueur à suivre suffisamment documenté.');return `<div class="players-grid">${panel('Compositions probables',p.lineups?`<p class="copy">Les compositions issues de l’API sont disponibles et seront affichées dès leur normalisation complète.</p>`:empty('Les compositions ne sont pas encore confirmées.'))}${panel('Absents & incertains',`<div class="grid two">${abs(vm.identity.home,p.absences.home)}${abs(vm.identity.away,p.absences.away)}</div>`)}</div><div style="margin-top:10px">${panel('Joueurs à suivre',watches)}</div><div style="margin-top:10px">${panel('Projections joueurs',p.projections.length?`<p class="copy">${p.projections.length} projection(s) calculée(s) à partir des données joueurs validées.</p>`:empty('Aucune projection joueur fiable pour ce match.'))}</div>`}

function render(raw){const vm=IasharkMatchViewModel.buildMatchViewModel(raw);document.title=`${vm.identity.home.name} vs ${vm.identity.away.name} — IASHARK`;root.innerHTML=`<article class="match-card">${header(vm)}<div class="tab-panel" id="summary">${summary(vm)}</div><div class="tab-panel" id="advanced" hidden>${advanced(vm)}</div><div class="tab-panel" id="players" hidden>${players(vm)}</div></article>`;root.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{root.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===btn));root.querySelectorAll('.tab-panel').forEach(x=>x.hidden=x.id!==btn.dataset.tab)}))}
async function init(){try{const id=typeof FIXED_MATCH_ID!=='undefined'?String(FIXED_MATCH_ID):new URLSearchParams(location.search).get('id');let raw=typeof PRELOADED_MATCH!=='undefined'?PRELOADED_MATCH:null;if(!raw){const data=await fetch(`/data.json?t=${Date.now()}`).then(r=>r.json());raw=(data.matchs||[]).find(x=>String(x.id)===String(id))}if(!raw)throw new Error('Match introuvable');render(raw)}catch(e){root.innerHTML=`<div class="loading-card"><p>${esc(e.message||'Erreur de chargement')}</p><a class="btn-login" href="/">Retour à l’accueil</a></div>`}}
init();
})();
