(function(){'use strict';
const root=document.getElementById('matchRoot');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number.isFinite(Number(v))?Number(v).toLocaleString('fr-FR',{maximumFractionDigits:1}):'—';
const empty=t=>`<div class="empty">${esc(t)}</div>`;
const logo=(url,name)=>url?`<img src="${esc(url)}" alt="${esc(name)}">`:'';
const panel=(title,body,cls='')=>`<section class="panel ${cls}"><h2 class="panel-title">${esc(title)}</h2>${body}</section>`;
const list=(items,cls='detail-list')=>`<ul class="${cls}">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
function header(vm){const i=vm.identity;return `<header class="match-head"><div class="meta-row"><div class="league">${logo(i.league.logo,i.league.name)}<span>${esc(i.league.name)}</span></div><span>${esc(i.date||'Date à confirmer')} · ${esc(i.time||'—')}</span></div><div class="teams"><div class="team">${logo(i.home.logo,i.home.name)}<h1>${esc(i.home.name)}</h1><small>Domicile</small></div><div class="versus"><b>VS</b><i></i></div><div class="team">${logo(i.away.logo,i.away.name)}<h1>${esc(i.away.name)}</h1><small>Extérieur</small></div></div><div class="venue">${vm.conditions.venue?`⌾ ${esc(vm.conditions.venue)}`:'Lieu à confirmer'}${vm.model.available?' <span>● Analyse disponible</span>':''}</div><div class="tabs" role="tablist" aria-label="Analyse du match"><button class="tab active" role="tab" aria-selected="true" data-tab="summary">Résumé</button><button class="tab" role="tab" aria-selected="false" data-tab="advanced">Données avancées</button><button class="tab" role="tab" aria-selected="false" data-tab="players">Joueurs</button></div></header>`}
function decision(vm){const r=vm.model.recommendation;if(!r)return empty(vm.model.unavailableReason);return `<div class="decision"><div><span class="micro">Décision IASHARK</span><h3>${esc(r.market)}</h3></div><div class="decision-metrics"><div><b>${fmt(r.probability)} %</b><small>Probabilité IASHARK</small></div>${r.reliability?`<div><b>${esc(r.reliability)}</b><small>Fiabilité</small></div>`:''}</div></div>`}
function factors(vm){const rows=[...vm.editorial.reasons];if(vm.editorial.decisiveFactor)rows.push(vm.editorial.decisiveFactor);return rows.length?`<div class="factor-grid">${rows.slice(0,3).map((x,i)=>`<div><i>${i===0?'↗':i===1?'◉':'◎'}</i><span>${esc(x)}</span></div>`).join('')}</div>`:empty('Les facteurs détaillés seront publiés dès que les données seront suffisamment complètes.')}
function markets(vm){const rows=vm.model.marketsCompared.length?vm.model.marketsCompared:(vm.model.recommendation?[{market:vm.model.recommendation.market,probability:vm.model.recommendation.probability,consensus:null,edge:null}]:[]);return rows.length?`<table class="market-table"><thead><tr><th>Marché</th><th>Prob. IASHARK</th><th>Consensus</th><th>Écart</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.market)}</td><td>${fmt(x.probability)} %</td><td>${x.consensus===null?'—':`${fmt(x.consensus)} %`}</td><td class="${x.edge>0?'positive':''}">${x.edge===null?'—':`${x.edge>0?'+':''}${fmt(x.edge)} pts`}</td></tr>`).join('')}</tbody></table>`:empty('Aucun marché comparable ne franchit encore les seuils du moteur.')}
function scenario(vm){const slots=vm.editorial.scenario15;if(!slots.length)return vm.editorial.scenario?`<p class="copy">${esc(vm.editorial.scenario)}</p>`:empty('Scénario indisponible.');const groups=[[slots[0],slots[1]],[slots[2],slots[3]],[slots[4],slots[5]]];return `<div class="scenario">${groups.map((items,i)=>{const available=items.filter(Boolean);if(!available.length)return'';const label=['0–30′','30–60′','60–90′'][i];return `<span>${label}</span><p>${esc(available.map(x=>x.txt).filter(Boolean).join(' '))}</p>`}).join('')}</div>`}
function summary(vm){return `<div class="summary-top">${panel('Lecture du match',vm.editorial.reading?`<p class="copy">${esc(vm.editorial.reading)}</p>`:empty('Lecture en attente de données fiables.'))}${panel('Décision IASHARK',decision(vm))}</div>${panel('Pourquoi ce choix ?',factors(vm),'summary-factors')}<div class="risk-strip"><b>⚠ Risque principal</b><span>${esc(vm.editorial.risk||'Risque spécifique non disponible dans les données actuelles.')}</span></div><div class="summary-bottom">${panel('Marchés comparés',markets(vm))}${panel('Scénario probable',scenario(vm))}</div>`}
function probabilities(vm){const p=vm.model.probabilities;if(!p)return empty('Probabilités indisponibles.');return `<div class="probabilities"><div><span>Domicile</span><strong>${fmt(p.home)}%</strong></div><div><span>Nul</span><strong>${fmt(p.draw)}%</strong></div><div><span>Extérieur</span><strong>${fmt(p.away)}%</strong></div></div>`}
function xg(vm){const x=vm.model.expectedGoals;if(!x)return empty('xG indisponibles.');return `<div class="xg-teams"><div>${logo(vm.identity.home.logo,vm.identity.home.name)}<strong>${fmt(x.home)}</strong><small>${esc(vm.identity.home.name)}</small></div><div>${logo(vm.identity.away.logo,vm.identity.away.name)}<strong>${fmt(x.away)}</strong><small>${esc(vm.identity.away.name)}</small></div></div>`}
function scores(vm){return vm.model.scores.length?vm.model.scores.map(s=>`<div class="score"><b>${esc(s.score)}</b><span>${fmt(s.probability)} %</span></div>`).join(''):empty('Scores indisponibles.')}
function conditions(vm){const w=vm.conditions.weather;return `<div class="condition-grid"><div><small>Stade</small><b>${esc(vm.conditions.venue||'À confirmer')}</b></div><div><small>Météo</small><b>${w?esc(w.description||w.temperature):'À confirmer'}</b></div>${w&&w.temperature?`<div><small>Température</small><b>${esc(w.temperature)}</b></div>`:''}</div>`}
function referee(vm){const a=vm.referee;if(!a)return empty('Arbitre non encore désigné ou données disciplinaires indisponibles.');return `<div class="referee"><b>${esc(a.name)}</b><div><span>${fmt(a.cardsPerMatch)}</span><small>Cartons / match</small></div><div><span>${fmt(a.penaltiesPerMatch)}</span><small>Penaltys / match</small></div><div><span>${fmt(a.matches)}</span><small>Matchs analysés</small></div></div>`}
function comparison(vm){if(!vm.comparison)return empty('Comparaison indisponible.');return `<div class="comparison">${vm.comparison.rows.map(r=>{const max=Math.max(r.home,r.away,1);return `<div class="compare-row"><b>${fmt(r.home)}</b><div class="bar"><i style="width:${r.home/max*100}%"></i></div><span>${esc(r.label)}</span><div class="bar away"><i style="width:${r.away/max*100}%"></i></div><b>${fmt(r.away)}</b></div>`}).join('')}</div>`}
function patterns(vm){if(!vm.patterns)return empty('Tranches de 15 minutes indisponibles : échantillon insuffisant.');const h=vm.patterns.home.slots||[],a=vm.patterns.away.slots||[],max=Math.max(...h.map(x=>+x.n||0),...a.map(x=>+x.n||0),1);return `<div class="patterns">${h.map((x,n)=>`<div><span>${fmt(x.n)}%</span><span>${fmt(a[n]&&a[n].n)}%</span><div><i style="height:${(+x.n||0)/max*54}px"></i><i style="height:${(+(a[n]&&a[n].n)||0)/max*54}px"></i></div><small>${esc(x.t)}</small></div>`).join('')}</div>`}
function quality(vm){return `<div class="quality-grid"><div><b>${esc(vm.model.agreementLabel||'—')}</b><small>Accord des modèles</small></div><div><b>${vm.model.simulationCount?Number(vm.model.simulationCount).toLocaleString('fr-FR'):'—'}</b><small>Simulations IA</small></div><div><b>${fmt(vm.model.quality)}%</b><small>Qualité des données</small></div><div><b>${vm.model.sources.length}</b><small>Sources confirmées</small></div></div>`}
function faq(vm){return `<div class="faq"><details open><summary>Pourquoi ce marché est-il retenu ?</summary><p>Il obtient le meilleur compromis calculé entre probabilité, fiabilité des données et cote admissible parmi les marchés modélisés.</p></details><details><summary>D’où viennent les données ?</summary><p>${esc(vm.model.sources.join(' · ')||'API-Football.')}</p></details><details><summary>Pourquoi certains blocs manquent-ils ?</summary><p>IASHARK masque une donnée lorsqu’elle n’est pas confirmée ou que son échantillon est insuffisant.</p></details></div>`}
function advanced(vm){return `<div class="context-top">${panel('Conditions du match',conditions(vm))}${panel('Arbitre & discipline',referee(vm))}</div><div class="advanced-top">${panel('Probabilités 1X2',probabilities(vm))}${panel('Buts attendus (xG)',xg(vm))}${panel('Scores les plus probables',scores(vm))}</div>${panel('Comparaison des équipes',comparison(vm),'advanced-wide')}${panel('Scénario par tranches de 15 min',patterns(vm),'advanced-wide')}${panel('Qualité, calcul et sources',quality(vm),'advanced-wide')}${panel('Questions sur ce match',faq(vm),'advanced-wide')}`}
function absences(vm){const side=(team,items)=>`<div><h3>${esc(team.name)}</h3>${items.length?list(items.map(x=>`${x.name}${x.reason?` — ${x.reason}`:''}`),'absence-list'):`<p class="muted">Aucune absence disponible dans les données.</p>`}</div>`;return `<div class="absence-cols">${side(vm.identity.home,vm.players.absences.home)}${side(vm.identity.away,vm.players.absences.away)}</div>`}
function lineups(vm){const l=vm.players.lineups;if(!l)return empty('Compositions probables — confirmation attendue environ une heure avant le match.');const pitch=(team,data)=>{if(!data||!Array.isArray(data.startXI)||!data.startXI.length)return `<div class="pitch-empty"><b>${esc(team.name)}</b><small>${esc(data?.formation||'Formation à confirmer')}</small><span>Onze non confirmé</span></div>`;const groups=['F','M','D','G'].map(pos=>data.startXI.filter(p=>p.pos===pos));return `<div class="pitch"><header><b>${esc(team.name)}</b><small>${esc(data.formation||'—')}</small></header><div class="pitch-lines">${groups.map(group=>`<div>${group.map(p=>`<span class="pitch-player" title="${esc(p.name)}"><i></i><em>${esc(p.name)}</em></span>`).join('')}</div>`).join('')}</div></div>`};return `<div class="lineup-grid">${pitch(vm.identity.home,l.home)}${pitch(vm.identity.away,l.away)}</div>`}
function watches(vm){return vm.players.watch.length?`<div class="watch-grid">${vm.players.watch.slice(0,3).map(x=>`<article class="watch">${x.photo?`<img src="${esc(x.photo)}" alt="">`:''}<b>${esc(x.name)}</b><small>${x.value!==null?`${fmt(x.value)} contribution(s) récente(s)`:'Joueur à suivre'}</small></article>`).join('')}</div>`:empty('Aucun joueur suffisamment documenté.')}
function projections(vm){if(!vm.players.projections.length)return empty('Aucune projection joueur fiable pour ce match.');return `<div class="table-scroll"><table class="projection-table"><thead><tr><th>Joueur</th><th>Marché</th><th>Statut</th><th>Minutes</th><th>Probabilité</th><th>Qualité</th></tr></thead><tbody>${vm.players.projections.slice(0,6).map(x=>`<tr><td>${esc(x.player)}</td><td>${esc(x.market)}</td><td>${esc(x.status)}</td><td>${x.minutes===null?'—':fmt(x.minutes)}</td><td>${x.probability===null?'—':`${fmt(x.probability)} %`}</td><td>${esc(x.quality)}</td></tr>`).join('')}</tbody></table></div>`}
function players(vm){return `<div class="players-top">${panel('Compositions probables',lineups(vm))}${panel('Absents & incertains',absences(vm))}</div>${panel('Joueurs à suivre',watches(vm),'players-wide')}${panel('Projections joueurs IASHARK',projections(vm),'players-wide')}<div class="scorer-lock"><b>Marché buteur</b><span>Disponible quand les compositions et les minutes attendues sont suffisamment fiables.</span></div>`}
function render(raw){const vm=IasharkMatchViewModel.buildMatchViewModel(raw);document.title=`${vm.identity.home.name} vs ${vm.identity.away.name} — IASHARK`;root.innerHTML=`<article class="match-card">${header(vm)}<main class="tab-panel" id="summary">${summary(vm)}</main><main class="tab-panel" id="advanced" hidden>${advanced(vm)}</main><main class="tab-panel" id="players" hidden>${players(vm)}</main></article>`;root.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{root.querySelectorAll('.tab').forEach(x=>{const active=x===btn;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active))});root.querySelectorAll('.tab-panel').forEach(x=>x.hidden=x.id!==btn.dataset.tab)}))}
async function init(){try{const id=typeof FIXED_MATCH_ID!=='undefined'?String(FIXED_MATCH_ID):new URLSearchParams(location.search).get('id');let raw=typeof PRELOADED_MATCH!=='undefined'?PRELOADED_MATCH:null;if(window.IasharkApp){const session=(await window.IasharkApp.supabase.auth.getSession()).data.session;if(session){const result=await window.IasharkApp.supabase.functions.invoke('match-data');if(result.data&&!result.error)raw=(result.data.matchs||[]).find(x=>String(x.id)===String(id))||raw}}if(!raw){const data=await fetch(`/data.json?t=${Date.now()}`).then(r=>r.json());raw=(data.matchs||[]).find(x=>String(x.id)===String(id))}if(!raw)throw new Error('Match introuvable');render(raw)}catch(e){root.innerHTML=`<div class="loading-card"><p>${esc(e.message||'Erreur de chargement')}</p><a class="btn-login" href="/">Retour à l’accueil</a></div>`}}
init();
})();
