name: Generer Videos LDC

on:
  workflow_dispatch:

jobs:
  creer_videos:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Lancer la vidéo
        env:
          ANTHROPIC_KEY:  ${{ secrets.ANTHROPIC_KEY }}
          CREATOMATE_KEY: ${{ secrets.CREATOMATE_KEY }}
        run: node test-video.js
